language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=ounit OUNIT_CI=true PINS="ounit:. ounit-lwt:."
    - POST_INSTALL_HOOK="opam install -t re"
matrix:
  include:
    - apt:
        packages:
          - libxml2-utils
      os: linux
      env: OCAML_VERSION=4.08 PACKAGE="ounit"

    - os: linux
      env: OCAML_VERSION=4.08 PACKAGE="ounit-lwt"

    - os: linux
      env: OCAML_VERSION=4.08 PACKAGE="ounit" REVDEPS=true

    # Use oldest possible version for backward compatibility.
    - os: linux
      env: OCAML_VERSION=4.02 PACKAGE="ounit"

    - os: osx
      env: OCAML_VERSION=4.08 PACKAGE="ounit"
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew

    - os: osx
      env: OCAML_VERSION=4.08 PACKAGE="ounit-lwt"
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
